version: "3.9"

services:
  api:
    build: .
    container_name: "api-teddy"
    ports:
      - 3500:3500
    env_file: ".env.docker"
    depends_on:
      - db
  db:
    container_name: "db-teddy"
    image: mysql:8.4
    ports:
      - 5006:3306
    environment:
      MYSQL_ROOT_PASSWORD: "12344321"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12344321"
      MYSQL_DATABASE: "teddy"
