services:
  db:
    container_name: "db-teddy"
    image: mysql:8.4
    ports:
      - 5006:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./database:/var/lib/mysql
  api:
    build: .
    container_name: "api-teddy"
    ports:
      - 3500:3500
    environment:
      SERVER_HOST: ${HOST}
      SERVER_PORT: ${PORT}
      SERVER_DOMAIN: ${DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    links:
      - "db:db"